title: UAC Bypass Using MSConfig Token Modification - File
status: test
description: Detects the pattern of UAC Bypass using a msconfig GUI hack (UACMe 55)
references:
    - https://github.com/hfiref0x/UACME
tags:
    - attack.defense-evasion
    - attack.privilege-escalation
    - attack.t1548.002
author: Amr Ashraf
logsource:
    category: file_event (EID 11)
    service: sysmon
    product: windows
detection:
    selection:
        TargetFilename|startswith: 'C:\Users\'
        TargetFilename|endswith: '\AppData\Local\Temp\pkgmgr.exe'
    condition: selection
falsepositives:
    - Unknown
level: high

