title: Detect Chocolatey Deployment
status: Developed
description: Detects the use of Chocolatey package manager to deploy software like 7-Zip, which could indicate unauthorized deployment.
author: Amr Ashraf
date: 2024-12-06
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    EventID: 4688
    CommandLine|contains:
      - 'choco install'
      - '7zip'
    NewProcessName|endswith:
      - '\Chocolatey\choco.exe'
  condition: selection
fields:
  - CommandLine
  - Image
  - ParentImage
  - User
falsepositives:
  - Legitimate use of Chocolatey for software deployment.
level: medium
tags:
  - attack.execution
  - T1072
VQL:
    LET ID_1494 = (
        CommandLine =~ "(?=.*choco install|.*7zip)" AND
        NewProcessName =~ "\\Chocolatey\\\\choco\\.exe$"
    )
