title: UAC Bypass Using MSConfig Token Modification - Process
status: Developed
author: Amr Ashraf
date: 2024/11/09
description: Detects the pattern of UAC Bypass using a msconfig GUI hack (UACMe 55)
tags:
    - attack.defense-evasion
    - attack.privilege-escalation
    - attack.t1548.002
logsource:
    category: process_creation
    product: windows
detection:
    process_creation:
        EventID: 4688
        Channel: Security
    selection:
        CommandLine: '"C:\Windows\system32\msconfig.exe" -5'
        MandatoryLabel:
            - S-1-16-12288
            - S-1-16-16384
        ParentProcessName|endswith: \AppData\Local\Temp\pkgmgr.exe
    condition: process_creation and selection
falsepositives:
    - Unknown
level: high