title: Mshtml.DLL RunHTMLApplication Suspicious Usage
description: |
    Detects execution of commands that leverage the "mshtml.dll" RunHTMLApplication export to run arbitrary code via different protocol handlers (vbscript, javascript, file, http...)
status: Developed
author: Amr Ashraf
date: 2024/11/09
tags:
    - attack.defense-evasion
    - attack.execution
logsource:
    category: process_creation
    product: windows
detection:
    process_creation:
        EventID: 4688
        Channel: Security
    selection:
        CommandLine|contains|all:
            - \..\
            - mshtml
        CommandLine|contains:
            - '#135'
            - RunHTMLApplication
    condition: process_creation and selection
falsepositives:
    - Unlikely
level: high
ruletype: Sigma
