title: Security Support Provider (SSP) Added to LSA Configuration
status: Experimental
description: |
    Detects the addition of a SSP to the registry. Upon a reboot or API call, SSP DLLs gain access to encrypted and plaintext passwords stored in Windows.
references:
    - https://powersploit.readthedocs.io/en/latest/Persistence/Install-SSP/
    - https://github.com/EmpireProject/Empire/blob/08cbd274bef78243d7a8ed6443b8364acd1fc48b/data/module_source/persistence/Install-SSP.ps1#L157
author: Amr Ashraf
date: 2024/12/23
tags:
    - attack.credential_access
    - attack.t1547.005
logsource:
    category: registry_event
    product: windows
detection:
    selection:
        EventID: 
            - 12
            - 13
        TargetObject|endswith:
            - '\Control\Lsa\Security Packages'
            - '\Control\Lsa\OSConfig\Security Packages'
    filter_main_msiexec:
        EventID: 
            - 12
            - 13
        Image|contains:
            - 'msiexec.exe'
    condition: selection and not 1 of filter_main_*
falsepositives:
    - Unknown
level: high
