title: Windows Installed Applications Information discovery via registry [medium]
status: test
description: System Information Discovery using Commandline utility
references:
    - Threat intel feed "https://andreacristaldi.github.io/APTmap/"
tags:
    - attack.discovery
    - attack.t1082
author: Amr Ashraf
logsource:
    product: Windows
    category: process_execution
detection:
    selection:
        CommandLine|contains: 
          - 'SOFTWARE\Wow6432\Microsoft\Windows\CurrentVersion\Uninstall'
          - 'SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall'
    condition: selection
falsepositives:
    - legitemate use
level: medium

