title: DFE-006-E-000-0030-Pcalua Application Compatibility Execution
id: dfe-006-e-000-0030
status: experimental
description: Detects pcalua.exe execution which can be used for defense evasion and bypassing application whitelisting
references:
    - https://attack.mitre.org/techniques/T1202/
    - https://lolbas-project.github.io/lolbas/Binaries/Pcalua/
author: HexaPrime Detection Team
date: 2025/12/13
tags:
    - attack.T1202
    - attack.defense_evasion
logsource:
    product: windows
    category: process_creation
detection:
    selection:
        Image|endswith: '\pcalua.exe'
        CommandLine|contains:
            - '-a'
            - '-m'
    condition: selection
falsepositives:
    - Legitimate application compatibility operations
    - Legacy application execution
level: medium