title: Rundll32 JS RunHTMLApplication Pattern
description: Detects suspicious command line patterns used when rundll32 is used to run JavaScript code
status: Experimental
author: Amr Ashraf
date: 2024/11/09
tags:
    - attack.defense-evasion
logsource:
    category: process_creation
    product: windows
detection:
    process_creation:
        EventID: 4688
        Channel: Security
    selection1:
        CommandLine|contains|all:
            - 'rundll32'
            - 'javascript'
            - '..\..\mshtml,'
            - 'RunHTMLApplication'
    selection2:
        CommandLine|contains: ';document.write();GetObject("script'
    condition: process_creation and (1 of selection*)
    VQL:
        LET ID_1098 = (
            CommandLine =~ "(?=.*rundll32)(?=.*javascript)(?=.*\\..\\..\\mshtml,)(?=.*RunHTMLApplication)" OR
            CommandLine =~ ";document.write();GetObject\\(\"script"
        )
falsepositives:
    - Unlikely
level: high

