title: Detect WMI Application Uninstallation
status: Developed
description: Detects the use of WMI to uninstall applications.
author: Amr Ashraf
date: 2024-12-06
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    EventID: 4688
    CommandLine|contains|all:
      - 'wmic '
      - 'call uninstall'
  condition: selection
fields:
  - EventID
  - CommandLine
  - Image
  - ParentImage
  - User
falsepositives:
  - Legitimate administrative tasks
level: high
tags:
  - attack.defense_evasion
  - attack.t1033
