title: Run Once Task Configuration in Registry
status: Developed
description: Rule to detect the configuration of Run Once registry key. Configured payload can be run by runonce.exe /AlternateShellStartup
references:
    - https://twitter.com/pabraeken/status/990717080805789697
    - https://lolbas-project.github.io/lolbas/Binaries/Runonce/
author: Amr Ashraf
date: 2024/12/23
tags:
    - attack.defense-evasion
    - attack.t1112
logsource:
    product: windows
    category: registry_event
detection:
    selection:
        EventID: 13
        TargetObject|contains: '\Microsoft\Active Setup\Installed Components'
        TargetObject|endswith: '\StubPath'
    filter_optional_chrome:
        EventID: 13
        Details|contains|all:
            - 'C:\Program Files\Google\Chrome\Application\'
            - '\Installer\chrmstp.exe" --configure-user-settings --verbose-logging --system-level' # In some cases the Details will contain an additional flag called "--channel=stable" at the end
    filter_optional_edge:
        EventID: 13
        Details|contains:
            - 'C:\Program Files (x86)\Microsoft\Edge\Application\'
            - 'C:\Program Files\Microsoft\Edge\Application\'
        Details|endswith: '\Installer\setup.exe" --configure-user-settings --verbose-logging --system-level --msedge --channel=stable'
    condition: selection and not 1 of filter_optional_*
falsepositives:
    - Legitimate modification of the registry key by legitimate program
level: medium
